# -*- coding: utf-8 -*-
"""Entrega Trabajo NYC grupo 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mh9Df7XjyCJlhm3doTC_IGvwZdGljDO-

# Caso 2 – Movilidad urbana y demanda de transporte
*Dataset base: NYC Yellow Taxi Trips – NYC*
Open Data / Kaggle
Enriquecimiento sugerido:
* Datos del clima (OpenWeatherMap API)
* Eventos públicos (NYC Events API)
* Precios de Uber/Lyft scrapeados o públicos.


**Pregunta de negocio:**
¿Cómo varían la demanda y los precios de transporte según la hora, el
clima y los eventos en la ciudad?

**Valor para la empresa:** Permite a plataformas de movilidad optimizar la distribución de
conductores y la fijación dinámica de precios.

### El entregable PC1 contiene las siguientes secciones:
1. Portada del equipo: nombre del caso, integrantes, roles asignados.
2. Descripción del problema de negocio: ¿qué empresa ficticia o real lo enfrenta? ¿por qué es relevante? (máx. 1 página).
3. Descripción de los datos: fuente principal, fuente de enriquecimiento, número de registros,
variables clave.
4. EDA Inicial: al menos 5 visualizaciones comentadas (distribuciones, valores nulos, primeras
correlaciones).
5. Hipótesis de negocio: mínimo 3 hipótesis que el equipo investigará en la Etapa 2,
redactadas como preguntas de negocio.
6. Plan de trabajo Etapa 2: qué hará cada integrante en las semanas 7–14 (tabla simple).
7. Apéndice de uso de IA: si usaron IA generativa, detallar qué prompts usaron y cómo
validaron los resultados.
* Todo debe ser documentado en un .md y subido a github
"""

!pip install pyspark

from google.colab import drive
drive.mount('/content/drive')

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, hour, dayofweek, to_date
import matplotlib.pyplot as plt
import seaborn as sns
spark = SparkSession.builder.appName("NYC_Taxi_Trips_Spark").getOrCreate()

print("SparkSession creada.")

# 1. Cargar viajes (usando Octubre de 2021 para que coincida con el clima)
df_uber_spark = spark.read.parquet('/content/drive/MyDrive/Data_Analytics_grupo_1/fhvhv_tripdata_2021-10.parquet')

# 2. Cargar Clima
df_clima_spark = spark.read.csv('/content/drive/MyDrive/Data_Analytics_grupo_1/New York City 2021-10-01 to 2024-03-14.csv', header=True, inferSchema=True)

# 3. Cargar Zonas
df_zonas_spark = spark.read.csv('/content/drive/MyDrive/Data_Analytics_grupo_1/taxi_zone_lookup.csv', header=True, inferSchema=True)

print("Archivos cargados correctamente")

print("\nEsquema de df_uber_spark:")
df_uber_spark.printSchema()

print("\nEsquema de df_clima_spark:")
df_clima_spark.printSchema()

print("\nEsquema de df_zonas_spark:")
df_zonas_spark.printSchema()

"""#Limpieza y exploración

### `df_clima_spark`
"""

# 1. Comprobar valores nulos en df_clima_spark
print("Valores nulos en df_clima_spark (ejemplo para 'precip'):")
df_clima_spark.filter(col("precip").isNull()).count()

# 2. Convertir la columna 'datetime' a tipo Timestamp
df_clima_spark = df_clima_spark.withColumn("datetime", col("datetime").cast("timestamp"))

# 3. Revisar tipos de datos y mostrar algunas filas
print("\nInformación de df_clima_spark después de la limpieza:")
df_clima_spark.printSchema()
df_clima_spark.show(5)

"""### `df_zonas_spark`"""

# 1. Comprobar valores nulos en df_zonas_spark (ejemplo para 'Zone')
print("Valores nulos en df_zonas_spark (ejemplo para 'Zone'):")
df_zonas_spark.filter(col("Zone").isNull()).count()

# 2. Revisar tipos de datos y mostrar algunas filas
print("\nInformación de df_zonas_spark:")
df_zonas_spark.printSchema()
df_zonas_spark.show(5)

# 3. Mostrar valores únicos para columnas categóricas
print("\nValores únicos en 'Borough':")
df_zonas_spark.select("Borough").distinct().show()
print("Valores únicos en 'service_zone':")
df_zonas_spark.select("service_zone").distinct().show()

"""### EDA: Extracción de Características Temporales de `df_uber_spark`"""

# Convertir 'pickup_datetime' a tipo Timestamp
df_uber_spark = df_uber_spark.withColumn("pickup_datetime", col("pickup_datetime").cast("timestamp"))

# Extraer la hora del día y el día de la semana de 'pickup_datetime'
df_uber_spark = df_uber_spark.withColumn('pickup_hour', hour(col('pickup_datetime')))
df_uber_spark = df_uber_spark.withColumn('pickup_dayofweek', dayofweek(col('pickup_datetime')) - 2) # Lunes=0, Domingo=6 (Spark Sunday=1, Monday=2...)

print("Características temporales extraídas de df_uber_spark.")
df_uber_spark.select("pickup_datetime", "pickup_hour", "pickup_dayofweek").show(5)

# Convertir df_clima_spark y df_zonas_spark a Pandas DataFrames.
df_clima = df_clima_spark.toPandas()
print("df_clima (Pandas) creado a partir de df_clima_spark.")
display(df_clima.head())

df_zonas = df_zonas_spark.toPandas()
print("df_zonas (Pandas) creado a partir de df_zonas_spark.")
display(df_zonas.head())

"""**Análisis del Clima (df_clima)**
* Este bloque integra datos externos (clima de NYC) para explicar cambios en la demanda. Variables como la sensación térmica (mínima de -26°C) y la lluvia (máximo de 60.9 mm) permiten identificar umbrales críticos donde caminar no es opción y el uso de Uber se vuelve indispensable. Este enriquecimiento es la base para proponer tarifas dinámicas y predecir picos de servicio ante climas extremos.

**Geografía del Negocio (df_zonas)**
* Esta tabla traduce los IDs de ubicación a nombres reales de distritos (Boroughs) y zonas. Es fundamental para segmentar el mercado: mientras Manhattan lidera en volumen, distritos como Brooklyn o Queens permiten analizar la sensibilidad del usuario en zonas residenciales. Estos datos permiten al equipo proponer incentivos geolocalizados y optimizar la distribución de la flota según la zona de servicio.

## `df_clima`
"""

import pandas as pd

# 1. Comprobar valores nulos en df_clima
print("Valores nulos en df_clima:")
display(df_clima.isnull().sum()[df_clima.isnull().sum() > 0])

# 2. Convertir la columna 'datetime' a tipo datetime
df_clima['datetime'] = pd.to_datetime(df_clima['datetime'])

# 3. Revisar tipos de datos y memoria utilizada
print("\nInformación de df_clima después de la limpieza:")
df_clima.info()

# 4. Mostrar estadísticas descriptivas para df_clima
print("\nEstadísticas descriptivas para df_clima:")
display(df_clima.describe())

"""**Interpretación:** El análisis descriptivo del clima revela una volatilidad térmica extrema en NYC, con sensaciones térmicas que alcanzan los -26°C.

#Visualizaciones
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
df_uber = df_uber_spark.sample(fraction=0.01, seed=42).toPandas()

df_uber['pickup_hour'] = df_uber['pickup_datetime'].dt.hour
df_uber['pickup_dayofweek'] = df_uber['pickup_datetime'].dt.dayofweek # Lunes=0, Domingo=6

print("Características temporales extraídas de df_uber.")

"""## Visualización 1: Distribución de la distancia del viaje (trip_miles)

"""

plt.figure(figsize=(10, 6))
sns.histplot(df_uber['trip_miles'], bins=50, kde=True)
plt.title('Distribución de la Distancia del Viaje (trip_miles)')
plt.xlabel('Millas del Viaje')
plt.ylabel('Frecuencia')
plt.xlim(0, df_uber['trip_miles'].quantile(0.99)) # Limitar el eje x para una mejor visualización
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

"""Interpretación: Existe una alta concentración de viajes en distancias cortas (menos de 5 millas). Esto indica que Uber se utiliza principalmente para tramos internos dentro de los condados de NYC, funcionando como un complemento o sustituto del transporte público para distancias medias.

## Visualización 2: Distribución de la duración del viaje (trip_time)
"""

plt.figure(figsize=(10, 6))
sns.histplot(df_uber['trip_time'] / 60, bins=50, kde=True) # Convertir a minutos
plt.title('Distribución de la Duración del Viaje (en minutos)')
plt.xlabel('Duración del Viaje (minutos)')
plt.ylabel('Frecuencia')
plt.xlim(0, (df_uber['trip_time'] / 60).quantile(0.99))
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

"""Interpretación: La mayoría de los viajes duran entre 10 y 25 minutos. La "cola larga" del gráfico muestra que los viajes extensos son poco frecuentes, lo que sugiere que el tráfico denso de la ciudad limita la velocidad promedio, haciendo que incluso distancias cortas tomen un tiempo considerable.

## Visualización 3: Distribución de la tarifa base del pasajero (base_passenger_fare)
"""

plt.figure(figsize=(10, 6))
sns.histplot(df_uber['base_passenger_fare'], bins=50, kde=True)
plt.title('Distribución de la Tarifa Base del Pasajero')
plt.xlabel('Tarifa Base')
plt.ylabel('Frecuencia')
plt.xlim(0, df_uber['base_passenger_fare'].quantile(0.99))
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

"""Interpretación: La mayoría de las tarifas se agrupan en el rango de los $10 a $25. Esto confirma que el modelo de negocio en octubre de 2021 dependía de un alto volumen de transacciones de bajo costo individual.

## Visualización 4: Demanda de viajes por hora del día
"""

plt.figure(figsize=(12, 6))
sns.countplot(x='pickup_hour', data=df_uber, palette='viridis')
plt.title('Demanda de Viajes por Hora del Día')
plt.xlabel('Hora del Día')
plt.ylabel('Número de Viajes')
plt.xticks(rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""Interpretación: Se observa un patrón de "doble pico" laboral, pero con una diferencia clave: la demanda es mucho más alta y sostenida desde las 2:00 PM hasta las 8:00 PM. Esto sugiere que en la post-pandemia de 2021, los viajes de ocio o retorno a casa por la tarde superaron a los viajes matutinos de oficina.

## Visualización 5: Demanda de viajes por día de la semana
"""

plt.figure(figsize=(12, 6))
sns.countplot(x='pickup_dayofweek', data=df_uber, palette='plasma')
plt.title('Demanda de Viajes por Día de la Semana')
plt.xlabel('Día de la Semana (0=Lunes, 6=Domingo)')
plt.ylabel('Número de Viajes')
plt.xticks(ticks=range(7), labels=['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo'], rotation=45)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

"""Interpretación: La demanda es estable de lunes a jueves, pero se dispara los viernes y sábados. Esto valida la hipótesis de que el transporte HVFHS (Uber/Lyft) es el preferido para actividades sociales nocturnas donde el usuario prioriza la comodidad sobre el costo.

# Enriquecimiento con Datos de Clima y EDA de Correlación
"""

# 1. Preparar df_uber: Extraer fecha y calcular demanda diaria
df_uber['pickup_date'] = df_uber['pickup_datetime'].dt.date
daily_uber_demand = df_uber.groupby('pickup_date').size().reset_index(name='total_trips')
daily_uber_demand['pickup_date'] = pd.to_datetime(daily_uber_demand['pickup_date'])

print("Demanda diaria de Uber calculada.")
display(daily_uber_demand.head())

import pandas as pd

# 2. Preparar df_clima: Asegurar columna de fecha para la unión
df_clima['datetime'] = pd.to_datetime(df_clima['datetime']) # Asegurar que la columna es datetime
df_clima['datetime_date'] = df_clima['datetime'].dt.date
df_clima['datetime_date'] = pd.to_datetime(df_clima['datetime_date'])

print("Columna de fecha en df_clima preparada.")
display(df_clima.head())

# 3. Unir los DataFrames: Demanda diaria y datos de clima
merged_df = pd.merge(daily_uber_demand, df_clima, left_on='pickup_date', right_on='datetime_date', how='inner')

print("DataFrames unidos correctamente.")
display(merged_df.head())

"""## Visualizaciones de Correlación: Demanda vs. Clima

###Visualización 6: Demanda diaria vs. Temperatura Máxima
"""

plt.figure(figsize=(12, 6))
sns.regplot(x='tempmax', y='total_trips', data=merged_df, scatter_kws={'alpha':0.6}, line_kws={'color':'red'})
plt.title('Demanda Diaria de Viajes vs. Temperatura Máxima')
plt.xlabel('Temperatura Máxima (°C)')
plt.ylabel('Número Total de Viajes')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

"""Interpretación: El gráfico de regresión muestra una tendencia ligeramente positiva. A medida que la temperatura es más moderada, el número total de viajes tiende a estabilizarse al alza. Sin embargo, la dispersión sugiere que la temperatura por sí sola no dicta la demanda, sino que interactúa con otros factores como la hora.

### Visualización 7: Demanda diaria vs. Precipitación
"""

plt.figure(figsize=(12, 6))
sns.scatterplot(x='precip', y='total_trips', data=merged_df, hue='conditions', size='total_trips', sizes=(20, 400), alpha=0.7)
plt.title('Demanda Diaria de Viajes vs. Precipitación')
plt.xlabel('Precipitación (mm)')
plt.ylabel('Número Total de Viajes')
plt.grid(True, linestyle='--', alpha=0.7)
plt.show()

"""Interpretación: Se observa que en los días lluviosos, el volumen de viajes se mantiene alto pero más disperso. El tamaño de las burbujas indica que los días lluviosos pueden generar picos de demanda donde el usuario busca refugio del clima, lo que suele activar las tarifas dinámicas.

###Visualización 8: Demanda diaria por Condición Climática
"""

plt.figure(figsize=(14, 7))
sns.boxplot(x='conditions', y='total_trips', data=merged_df, palette='coolwarm')
plt.title('Demanda Diaria de Viajes por Condición Climática')
plt.xlabel('Condición Climática')
plt.ylabel('Número Total de Viajes')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# Comentario: Esta visualización nos permitirá comparar la distribución de la demanda en diferentes condiciones climáticas (e.g., 'clear', 'rain', 'snow'). Se espera que los días claros tengan una demanda mayor y más estable que los días con condiciones adversas.

"""Interpretación: Los días con "Clear" (despejado) tienen una mediana de viajes más alta y consistente. Por el contrario, los días con condiciones mixtas (lluvia/nubes) muestran "outliers" (puntos fuera de la caja), lo que significa que el clima inestable provoca una demanda impredecible, dificultando la planificación de la flota de conductores.

## Visualización 9: Demanda de viajes por distrito (Borough)
"""

# 1. Unir df_uber_spark con df_zonas_spark para obtener el Borough de origen
df_uber_with_zones = df_uber_spark.join(df_zonas_spark, df_uber_spark.PULocationID == df_zonas_spark.LocationID, "inner")

# 2. Agrupar por 'Borough' y contar el número de viajes
demand_by_borough_spark = df_uber_with_zones.groupBy("Borough").count().orderBy(col("count").desc())

print("Demanda de viajes por distrito calculada en Spark.")
demand_by_borough_spark.show()

# 3. Convertir el resultado a Pandas DataFrame para visualización
demand_by_borough_pd = demand_by_borough_spark.toPandas()

plt.figure(figsize=(12, 7))
sns.barplot(x='Borough', y='count', data=demand_by_borough_pd, palette='crest', hue='Borough', legend=False)
plt.title('Demanda de Viajes por Distrito (Borough)')
plt.xlabel('Distrito (Borough)')
plt.ylabel('Número de Viajes')
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""* **Observación:** Manhattan concentra la gran mayoría de la demanda, con un volumen que casi duplica al de Brooklyn. Distritos como Staten Island o EWR tienen una demanda marginal en comparación.

* **Insight de Negocio:** La infraestructura de transporte público en Manhattan es densa, pero la demanda de Uber sigue siendo masiva. Esto sugiere que los usuarios eligen Uber por conveniencia o rapidez ante el clima neoyorquino. En distritos como Brooklyn y Queens, donde las distancias son mayores, la sensibilidad al clima podría ser un factor crítico para la rentabilidad de los conductores.

## Conclusión Inicial: Dinámica de la Demanda de Transporte en NYC

El análisis de los viajes de taxi y HVFHS (Uber/Lyft) en NYC para octubre de 2021, junto con datos climáticos y geográficos, revela patrones claros en la demanda de transporte:

*   **Demanda Concentrada y de Corta Distancia**: La mayoría de los viajes son de distancias cortas (menos de 5 millas) y duraciones de 10-25 minutos, sugiriendo un uso para tramos internos complementarios al transporte público.
*   **Patrones Temporales Definidos**: La demanda presenta un "doble pico" con un fuerte y sostenido aumento entre las 2:00 PM y las 8:00 PM, indicando una preponderancia de viajes vespertinos/nocturnos (ocio, regreso a casa). La demanda es estable de lunes a jueves, pero se dispara significativamente los viernes y sábados, validando su uso para actividades sociales.
*   **Influencia del Clima**: Las condiciones climáticas tienen un impacto notable. Mientras que las temperaturas moderadas estabilizan la demanda, la lluvia genera picos impredecibles (activando tarifas dinámicas), y los días despejados muestran una demanda más alta y consistente en comparación con días de clima mixto.
*   **Distribución Geográfica Desigual**: Manhattan domina la demanda de viajes, casi duplicando a Brooklyn. Esto sugiere que, a pesar de una densa red de transporte público, los usuarios de Manhattan priorizan la conveniencia y rapidez. En contraste, los distritos exteriores podrían ser más sensibles al clima para la rentabilidad de los conductores.

En resumen, la demanda de transporte en NYC está fuertemente influenciada por la hora del día, el día de la semana y las condiciones climáticas, con un claro impacto geográfico. Estos insights son cruciales para optimizar la distribución de conductores y la implementación de estrategias de precios dinámicos por parte de las plataformas de movilidad.
"""